l_spanish:
 at_artifact_price_qwa_desc: "Calidad y Riqueza"
 at_artifact_price_durability_desc: "Durabilidad"
 at_artifact_price_destroy_desc: "Común o obra maestra"
 at_artifact_price_unique_desc: "Único"
 at_artifact_ask_price_player_desc: "Margen de beneficio"
 at_artifact_ask_price_ai_greed_desc: "Avaricia del vendedor"
 at_artifact_bid_price_ai_greed_desc: "Avaricia del comprador"
