name: Release Upload
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    environment: e
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip code
        run: |
          cd  ${{ secrets.DIR }}/AGOTSpanish/AGOTSpanish/C/
          zip -r  ${{ secrets.DIR }}/AGOTSpanish/AGOTSpanish.zip *
          echo "Item Compresed"
      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN_RELEASE }}"
          automatic_release_tag: "lastest"
          prerelease: false
          title: "AGOT Spanish"
          files: |
             ${{ secrets.DIR }}/AGOTSpanish/AGOTSpanish.zip
      - name: "Removing Zip"
        run: |
          rm  ${{ secrets.DIR }}/AGOTSpanish/AGOTSpanish.zip
          echo "Zip Removed"
